"use strict";
exports.__esModule = true;
var Imdb_1 = require("./Imdb");
var Movie_1 = require("./Movie");
var fs = require("file-system");
var movie_1 = new Movie_1.Movie('Joker', 2019, 'estadounidense', 'suspense');
var movie_2 = new Movie_1.Movie('Parasito', 2019, 'coreana', 'suspense');
var peliculas = [movie_1, movie_2];
var imdb = new Imdb_1.Imdb(peliculas);
console.log(imdb);
var imdbJSON = JSON.stringify(imdb);
console.log(imdbJSON);
fs.writeFileSync('imdbBBDD.json', imdbJSON, { encoding: 'utf8', flag: 'a+', mode: 438 });
